import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.jsx";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const griffy = {
  variable: "--font-griffy",
};




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${griffy.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
